#############################################################################################################################
# Makefile initially created by Dev-C++ 5.11, manually modified thereafter. 												#
#############################################################################################################################
# Release mode only.																										#
#############################################################################################################################

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ../Resources/main.res
OBJ      = ../obj/Release/ai.o ../obj/Release/card.o ../obj/Release/entity.o ../obj/Release/globals.o ../obj/Release/load.o  ../obj/Release/save.o ../obj/Release/Windows/windows_main.o ../obj/Release/menu.o ../obj/Release/message.o ../obj/Release/misc.o ../obj/Release/picture.o ../obj/Release/process.o ../obj/Release/settings.o ../obj/Release/timebase.o ../obj/Release/engine.o ../obj/Release/log.o ../obj/Release/assets.o ../obj/Release/benchmark.o ../obj/Release/Renderer/renderer_double_buffer.o ../obj/Release/Windows/windows_procedure.o ../obj/Release/Renderer/renderer_direct_2d.o ../obj/Release/heap_allocator.o ../obj/Release/network.o ../obj/Release/path_finding.o ../obj/Release/Renderer/renderer.o ../obj/Release/Renderer/renderer_sdl.o ../obj/Release/Renderer/renderer_single_buffer.o ../obj/Release/sound.o ../obj/Release/Renderer/renderer_wireframe.o ../obj/Release/constants.o $(RES)
LINKOBJ  = ../obj/Release/ai.o ../obj/Release/card.o ../obj/Release/entity.o ../obj/Release/globals.o ../obj/Release/load.o  ../obj/Release/save.o ../obj/Release/Windows/windows_main.o ../obj/Release/menu.o ../obj/Release/message.o ../obj/Release/misc.o ../obj/Release/picture.o ../obj/Release/process.o ../obj/Release/settings.o ../obj/Release/timebase.o ../obj/Release/engine.o ../obj/Release/log.o ../obj/Release/assets.o ../obj/Release/benchmark.o ../obj/Release/Renderer/renderer_double_buffer.o ../obj/Release/Windows/windows_procedure.o ../obj/Release/Renderer/renderer_direct_2d.o ../obj/Release/heap_allocator.o ../obj/Release/network.o ../obj/Release/path_finding.o ../obj/Release/Renderer/renderer.o ../obj/Release/Renderer/renderer_sdl.o ../obj/Release/Renderer/renderer_single_buffer.o ../obj/Release/sound.o ../obj/Release/Renderer/renderer_wireframe.o ../obj/Release/constants.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows "../../../Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libgdi32.a" -m32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ../bin/Release/Gatherers.exe
CXXFLAGS = $(CXXINCS) -m32 -DRELEASE
CFLAGS   = $(INCS) -m32 -DRELEASE
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../obj/Release/ai.o: ../Source/ai.c
	$(CC) -c ../Source/ai.c -o ../obj/Release/ai.o $(CFLAGS)

../obj/Release/card.o: ../Source/card.c
	$(CC) -c ../Source/card.c -o ../obj/Release/card.o $(CFLAGS)

../obj/Release/entity.o: ../Source/entity.c
	$(CC) -c ../Source/entity.c -o ../obj/Release/entity.o $(CFLAGS)

../obj/Release/globals.o: ../Source/globals.c
	$(CC) -c ../Source/globals.c -o ../obj/Release/globals.o $(CFLAGS)

../obj/Release/load.o: ../Source/load.c
	$(CC) -c ../Source/load.c -o ../obj/Release/load.o $(CFLAGS)

../obj/Release/Windows/windows_main.o: ../Source/Windows/windows_main.c
	$(CC) -c ../Source/Windows/windows_main.c -o ../obj/Release/Windows/windows_main.o $(CFLAGS)

../obj/Release/menu.o: ../Source/menu.c
	$(CC) -c ../Source/menu.c -o ../obj/Release/menu.o $(CFLAGS)

../obj/Release/message.o: ../Source/message.c
	$(CC) -c ../Source/message.c -o ../obj/Release/message.o $(CFLAGS)

../obj/Release/misc.o: ../Source/misc.c
	$(CC) -c ../Source/misc.c -o ../obj/Release/misc.o $(CFLAGS)

../obj/Release/picture.o: ../Source/picture.c
	$(CC) -c ../Source/picture.c -o ../obj/Release/picture.o $(CFLAGS)

../obj/Release/process.o: ../Source/process.c
	$(CC) -c ../Source/process.c -o ../obj/Release/process.o $(CFLAGS)

../obj/Release/settings.o: ../Source/settings.c
	$(CC) -c ../Source/settings.c -o ../obj/Release/settings.o $(CFLAGS)

../obj/Release/timebase.o: ../Source/timebase.c
	$(CC) -c ../Source/timebase.c -o ../obj/Release/timebase.o $(CFLAGS)

../obj/Release/engine.o: ../Source/engine.c
	$(CC) -c ../Source/engine.c -o ../obj/Release/engine.o $(CFLAGS)

../obj/Release/log.o: ../Source/log.c
	$(CC) -c ../Source/log.c -o ../obj/Release/log.o $(CFLAGS)

../obj/Release/assets.o: ../Source/assets.c
	$(CC) -c ../Source/assets.c -o ../obj/Release/assets.o $(CFLAGS)

../obj/Release/benchmark.o: ../Source/benchmark.c
	$(CC) -c ../Source/benchmark.c -o ../obj/Release/benchmark.o $(CFLAGS)

../obj/Release/Renderer/renderer_double_buffer.o: ../Source/Renderer/renderer_double_buffer.c
	$(CC) -c ../Source/Renderer/renderer_double_buffer.c -o ../obj/Release/Renderer/renderer_double_buffer.o $(CFLAGS)
	
../obj/Release/Windows/windows_procedure.o: ../Source/Windows/windows_procedure.c
	$(CC) -c ../Source/Windows/windows_procedure.c -o ../obj/Release/Windows/windows_procedure.o $(CFLAGS)
	
../obj/Release/Renderer/renderer_direct_2d.o: ../Source/Renderer/renderer_direct_2d.c
	$(CC) -c ../Source/Renderer/renderer_direct_2d.c -o ../obj/Release/Renderer/renderer_direct_2d.o $(CFLAGS)
	
../obj/Release/heap_allocator.o: ../Source/heap_allocator.c
	$(CC) -c ../Source/heap_allocator.c -o ../obj/Release/heap_allocator.o $(CFLAGS)
	
../obj/Release/save.o: ../Source/save.c
	$(CC) -c ../Source/save.c -o ../obj/Release/save.o $(CFLAGS)
	
../obj/Release/network.o: ../Source/network.c
	$(CC) -c ../Source/network.c -o ../obj/Release/network.o $(CFLAGS)
	
../obj/Release/path_finding.o: ../Source/path_finding.c
	$(CC) -c ../Source/path_finding.c -o ../obj/Release/path_finding.o $(CFLAGS)

../obj/Release/Renderer/renderer.o: ../Source/Renderer/renderer.c
	$(CC) -c ../Source/Renderer/renderer.c -o ../obj/Release/Renderer/renderer.o $(CFLAGS)
	
../obj/Release/Renderer/renderer_sdl.o: ../Source/Renderer/renderer_sdl.c
	$(CC) -c ../Source/Renderer/renderer_sdl.c -o ../obj/Release/Renderer/renderer_sdl.o $(CFLAGS)
	
../obj/Release/Renderer/renderer_single_buffer.o: ../Source/Renderer/renderer_single_buffer.c
	$(CC) -c ../Source/Renderer/renderer_single_buffer.c -o ../obj/Release/Renderer/renderer_single_buffer.o $(CFLAGS)
	
../obj/Release/sound.o: ../Source/sound.c
	$(CC) -c ../Source/sound.c -o ../obj/Release/sound.o $(CFLAGS)
	
../obj/Release/Renderer/renderer_wireframe.o: ../Source/Renderer/renderer_wireframe.c
	$(CC) -c ../Source/Renderer/renderer_wireframe.c -o ../obj/Release/Renderer/renderer_wireframe.o $(CFLAGS)
	
../obj/Release/constants.o: ../Source/constants.c
	$(CC) -c ../Source/constants.c -o ../obj/Release/constants.o $(CFLAGS)
	
../Resources/main.res: ../Resources/main.rc 
	$(WINDRES) -i ../Resources/main.rc  -F pe-i386 --input-format=rc -o ../Resources/main.res -O coff
